### PR TITLE
Change names and patters in all files

### PR DESCRIPTION
**Pull request by janniss91**
sinst -> regpol
sodir -> semas
oempt -> noref
LK[V]MF[SO] -> VF[ADV]LK[V]MF[SO]
LK[V]MF[SO]Q -> LK[V]MF[SO]

### CODE REVIEW

**Review by DiveFish — CHANGES_REQUESTED** [review]
The following changes need to be done:
- In `german_ambiguous_gold.tsv` and `german_part-ambiguous_gold.tsv`, replace `LK[V]MF[SO]` by `VF[ADV]LK[V]MF[SO]`. Make sure to not rename those sentences which have been relabeled from `LK[V]MF[SO]Q` to `LK[V]MF[SO]`.
- Apply changes also to OS word order:
    - Rename `LK[V]MF[OS]` to `VF[ADV]LK[V]MF[OS]`.
    - Rename `LK[V]MF[OS]Q` to `LK[V]MF[OS]`.

**Comment by janniss91** [comment]
I have corrected the replacements in the two CSV files.
My approach was obviously wrong for these files.
This time I have worked with a temporary replacement for LK[V]MF[SO]Q  so it should have worked now.

I have also done the replacements for the OS word order.

**Review by DiveFish — CHANGES_REQUESTED** [review]
The tsv files now again include the `sinst`, `sodir` and `oempt` labels which should have been replaced by `regpol`, `semas` and `noref`, respectively.

**Comment by janniss91** [comment]
Ah sorry, this happened because I had to reset the files and forgot that these changes had to be made too.
I've replaced the patterns again.

**Review by DiveFish — APPROVED** [review]

**Pull request merged**
