### PR TITLE
Add conllu files

### PR DESCRIPTION
**Pull request by DiveFish**
I also added the `conllu` versions of the SORTS test suite files. I already tested them in `sticker2` without any problems.

### CODE REVIEW

**Comment by janniss91** [comment]
Looks good to me as well.
I have inspected all 4 files and it seems to be working fine.

Do you want me to check anything specific?

Maybe we could add a sentence in the Readme that hints at the fact that the Conll conversion scripts are in the PPATS repository?

**Comment by DiveFish** [comment]
> Looks good to me as well.
> I have inspected all 4 files and it seems to be working fine.
> 
> Do you want me to check anything specific?
> 
> Maybe we could add a sentence in the Readme that hints at the fact that the Conll conversion scripts are in the PPATS repository?

No, nothing specific. Just if I missed anything in the conversion.

Yes, good point. I was first thinking of merging the two repos into one big test suite repo. But SORTS has already been published and linked to in a paper, so it would be good to keep this repo.

**Comment by janniss91** [comment]
I'll merge after the commit with the change in the readme then.

**Comment by DiveFish** [comment]
> I'll merge after the commit with the change in the readme then.

Thanks for the reminder. I adjusted the readme accordingly.

**Pull request merged**
